### PR TITLE
Replace Axios with built-in fetch

### PR DESCRIPTION
**Pull request by jensdev**
Thank you for this package. We are not using axios in our app, but would like to use your package so I replaced it with fetch.

### CODE REVIEW

**Review by arlandantas — APPROVED** [review]

**Review by tschoffelen — COMMENTED** [review]
This looks good - only thought I have is whether this should be a major version upgrade since it will probably change the error message for network/HTTP errors that are thrown.

Any specific reason we should remove `axios` from the package?

**Comment by jensdev** [comment]
I guess it's personal preference `axios` vs `fetch`. But `fetch` is already included in RN.
I've added tests for unknonwn appId and changed Android to check the res.status, but it won't throw an error on 404 like `axios` does.

**Comment by jensdev** [comment]
@tschoffelen at the moment I'm using a patch. Would prefer to just upgrade :)

**Review by tschoffelen — APPROVED** [review]

**Comment by tschoffelen** [comment]
Published to NPM as `react-native-check-version@1.1.0`

**Pull request merged**
